#!/bin/sh

# turn off special handling of ._* files in tar, etc.
COPYFILE_DISABLE=1; export COPYFILE_DISABLE

cd /Applications/MAMP/htdocs/codereuse

cp -pr * /Users/tim/work/CodeReuse

cd /Users/tim/work

tar --exclude '.git' --exclude '.DS_Store' -czvf codereuse.tar.gz ./CodeReuse

# make sure CodeReuse_tar is existing folder
cp codereuse.tar.gz CodeReuse_tar

cd makefile_codereuse

sftp -P 49430 root@bms.closedarea.com < build_sftp.bat
ssh -T root@bms.closedarea.com -p 49430 < build_ssh.bat
