#!/bin/sh

# turn off special handling of ._* files in tar, etc.
COPYFILE_DISABLE=1; export COPYFILE_DISABLE

cd /Applications/MAMP/htdocs/codereuse

cp -r * /Users/tim/work/CodeReuse

cd /Users/tim/work

tar --exclude '.git' --exclude '.DS_Store' -czvf codereuse.tar.gz ./CodeReuse

cp codereuse.tar.gz CodeReuse_tar

cd makefile_codereuse

sftp -P 1024 root@bms.closedarea.com < build_sftp.bat
ssh -T root@bms.closedarea.com -p 1024 < build_ssh.bat
